### PR TITLE
Explain what a counting channel is

### LINKED ISSUE #183: Define counting channel
# Feature request

In the [README.md](https://github.com/countr/countr/blob/8826fb656e06fc51f7d66924893c73e33e818b96/README.md) it should define what a counting channel is inside the first paragraph. This would help when attracting users who discover this repo.

### PR DESCRIPTION
**Pull request by promise**
Fixes #183

### CODE REVIEW

**Review by itzJOHv — APPROVED** [review]

**Review by Ta1al — CHANGES_REQUESTED** [review]
I don't like this definition.

**Comment by promise** [comment]
@Ta1al do you have any other suggestions?

**Comment by Ta1al** [comment]
How about a GIF of people counting in all the different number formats?

**Comment by promise** [comment]
internal discussion; not adding this

**Pull request closed without merging**
